
patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: 904594193283.dkr.ecr.ap-southeast-1.amazonaws.com/samplewebapp
  newName: 904594193283.dkr.ecr.ap-southeast-1.amazonaws.com/samplewebapp
  newTag: ae68bd3e91b7b0213a6a4ba67f2d6d7ca197b509
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
